on: [push]

jobs:
  client_hello_world:
    runs-on: ubuntu-latest
    name: Fires up the client to talk to the app.
    container: docker
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Builds the docker composed image"
        id: build
        run: docker compose build
      - name: "Creates the docker compose image and runs the tests"
        id: run-test
        run: docker compose up --abort-on-container-exit --exit-code-from client